services:
  - type: web
    name: goldenmeraki-mt
    env: node
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ENABLE_SWAGGER
        value: false
      - key: CORS_ORIGIN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@goldenmeraki.com
      - key: ADMIN_PASSWORD
        sync: false
